services:

  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app-network
    restart: unless-stopped

  web-blue:
    image: orimolco/web-app:latest
    container_name: web-blue
    expose:
      - "8000"
    environment:
      - API_URL=http://nginx:3001
    networks:
      - app-network
    restart: unless-stopped
    profiles: ["blue"]

  web-green:
    image: orimolco/web-app:latest
    container_name: web-green
    expose:
      - "8000"
    environment:
      - API_URL=http://nginx:3001
    networks:
      - app-network
    restart: unless-stopped
    profiles: ["green"]

  api-blue:
    image: orimolco/api-service:latest
    container_name: api-blue
    expose:
      - "3000"
    networks:
      - app-network
    restart: unless-stopped
    profiles: ["blue"]

  api-green:
    image: orimolco/api-service:latest
    container_name: api-green
    expose:
      - "3000"
    networks:
      - app-network
    restart: unless-stopped
    profiles: ["green"]

networks:
  app-network:
    driver: bridge